google_analytics:
  enabled: true
  id: G-9TV7SDFVG2
  
# Enable or disable the RSS feed.
rss: true
highlight: rainbow
social_links:
  github: https://github.com/eddyli1989
  twitter: https://twitter.com/dashuai38953711
  mail: mailto:eddyli@outlook.com
